### ISSUE TITLE
"City" in error messages instead of "Country"

### ISSUE THREAD

**Issue by KosRud** [cl0ne/euro-diffusion#11]
`name` is the name of the country, cities have no names

https://github.com/cl0ne/euro-diffusion/blob/5a7cfdfa5a57a2c7bd49ffb01202be6fae8762bf/main.py#L39-L40

https://github.com/cl0ne/euro-diffusion/blob/0c6495853144868453839c0651b6c53136e88ba4/main.py#L44-L47

The coordinates for a city are 2 integers, while the country bounds are 4 integers

https://github.com/cl0ne/euro-diffusion/blob/0c6495853144868453839c0651b6c53136e88ba4/main.py#L36

**Comment by cl0ne** [comment]
Thanks, "you goddamn right".
