### ISSUE TITLE
Fail fast

### ISSUE THREAD

**Issue by KosRud** [cl0ne/euro-diffusion#9]
https://github.com/cl0ne/euro-diffusion/blob/0c6495853144868453839c0651b6c53136e88ba4/euro_diffusion/simulator.py#L28-L31

https://github.com/cl0ne/euro-diffusion/blob/0c6495853144868453839c0651b6c53136e88ba4/euro_diffusion/simulator.py#L63-L65

In case when list `countries` is empty it is already clear that something went wrong. There is no point in continuing execution with corrupted data

**Comment by cl0ne** [comment]
It'll just return an empty list in that case.

**Comment by KosRud** [comment]
https://github.com/cl0ne/euro-diffusion/blob/0c6495853144868453839c0651b6c53136e88ba4/main.py#L19-L20

the `countries` list is never supposed to be empty because if it is, the `Simulator` is not created

**Comment by cl0ne** [comment]
I know that and I don't see any reason why simulator cannot return empty list for empty input even if the client code won't cause this situation.
